#am_radio CONFIG

server:
  port: 9015
spring:
  application:
    name: am_radio
  datasource:
    url: jdbc:h2:file:./h2Database/h2Stations
    username: {AWS_AM_RADIO_USERNAME}
    password: {AWS_AM_RADIO_PASSWORD}
    driverClassName: org.h2.Driver
#    data: classpath:./am_radio.sql
    initialize: true
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true