#am_radio CONFIG - dev

server:
    port: 443

spring:
    application:
        name: am_radio
    h2:
        console:
            enabled: true
    datasource:
        url: ${RADIO_DB_URL}
        username: ${RADIO_DB_USERNAME}
        password: ${RADIO_DB_PASSWORD}
        driverClassName: org.h2.Driver
        initialize: true
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
                jdbc:
                    lob:
                        non_contextual_creation: true